Repository creative-system-consultant/fmsv2, pull requests merged in 2024-03, with the labels that each got.

#55 add 2 list to search: siskop and fms
  app/Livewire/Teller/DividendWithdrawal.php
  app/Models/Siskop/SiskopApplyDividend.php
  app/Services/Module/General/CustomerSearch.php
  resources/views/livewire/teller/dividend-withdrawal.blade.php
Labels: enhancement

#58 searching error
  app/Services/Module/General/CustomerSearch.php
Labels: bug

#60 Github action yml
  .github/workflows/main.yml
Labels: enhancement

#62 issue #61
  app/Livewire/General/CustomerSearch.php
  app/Livewire/Teller/DividendWithdrawal.php
Labels: bug

#66 issue #65
  app/Services/Module/General/CustomerSearch.php
  resources/views/livewire/teller/dividend-withdrawal.blade.php
Labels: bug

#68 issue #67
  app/Livewire/Teller/DividendWithdrawal.php
  resources/views/livewire/teller/dividend-withdrawal.blade.php
Labels: bug

#69 fix issue #13
  app/Livewire/Cif/Info/Address.php
  resources/views/livewire/cif/info/address.blade.php
Labels: bug

#71 fix issue #70
  app/Services/Module/General/CustomerSearch.php
Labels: bug

#73 fix issue #72
  app/Action/StoredProcedure/SpFmsUpTrxDivOutCash.php
  app/Livewire/Teller/DividendWithdrawal.php
  app/Services/Module/General/CustomerSearch.php
  resources/views/livewire/teller/dividend-withdrawal.blade.php
Labels: enhancement

#77 fix other info guarantor
  app/Livewire/Cif/Info/Guarantee.php
Labels: bug

#78 remove txn code from the sp param
  app/Action/StoredProcedure/SpFmsUpTrxSpecialAid.php
  app/Livewire/Teller/PaymentMember/Category/TabungKhairat.php
Labels: bug, enhancement

#81 add chart in screen dashboard
  app/Livewire/Home/Home.php
  app/Models/Fms/DividenRequest.php
  app/Models/Fms/FmsContributionRequest.php
  package-lock.json
  package.json
  resources/views/livewire/home/home.blade.php
Labels: enhancement
